language: node_js
node_js: node
cache:
  directories:
  - node_modules
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: Zcg/umJ8AxUVueLpDxsU0zNArEez1NaAhl6TFhUW7HTz7qjGK6BydqLBwxze1cDD1aR5dOGXTpRUrdVIzUTVMMT8xdPaEJq/1y0Dny0SjmbEMmztaemm8MX+7xKZDgUPZZIuibdjjyFW6u06FtAgJgEKyL2xn8qPSdah6QztwL/KhMFmIPyiZRfa/xRddVBJAFWzDn9dQMyS4G78GmtfN3Dr+P5Te0YUQfvAiacf/vqXONHkNW7b+uS5zxmhI8V630GTCAyWk4pQAe/Svr5vPLS3QhfPSI4SXvq+ZCh8SfkL4uohXOjvqpDfuqu9TeYRSgxZz1CtgloOwV5/HILFwM6/z2mKchPBpKTHg67I5eUTLX7IOfcebESfvujKZaVF7stjDTtaLPjZ0DYqRvmRU3rOylpbfwhtcLj47y4EPMHhPAu//imuT3hTgaRNDusepIh2YBz4D5xNy+kldtLuM2axmU9CYo5PXJJWFIeuGjioZtchaPcPHjWorSDkTLuWqKc71Zeic3wdLbIepiCJvphZ/vyxxfKwQQa69wlheru3EyFKAk/O6DFlhldLZm9uzLio69xVtZ1LCD99Bvw0MvhOyz2q04tqnYDBKDljjmnp5du9Gu7kz0VSq609BaXRfbpKURa1nYVMEufsWAEStAOD1mQc77vDcHMrqFw9MMY=
  app: beachtides-server
  on:
    repo: JacobMacInnis/beach-tides-server
